openapi: 3.0.0
info:
  title: 匿名掲示板API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: development
paths:
  /posts:
    get:
      description: 投稿をすべて取得する
      operationId: getPosts
      responses:
        '200':
          $ref: '#/components/responses/Posts'
    post:
      description: 投稿を作成する
      operationId: createPost
      requestBody:
        $ref: '#/components/requestBodies/Post'
      responses:
        '201':
          $ref: '#/components/responses/Post'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /posts/{postId}:
    get:
      description: 投稿を取得する
      operationId: getPost
      parameters:
        - $ref: '#/components/parameters/postIdParam'
      responses:
        '200':
          $ref: '#/components/responses/Post'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      description: 投稿を更新する
      operationId: updatePost
      parameters:
        - $ref: '#/components/parameters/postIdParam'
      requestBody:
        $ref: '#/components/requestBodies/Post'
      responses:
        '200':
          $ref: '#/components/responses/Post'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
    delete:
      description: 投稿を削除する
      operationId: deletePost
      parameters:
        - $ref: '#/components/parameters/postIdParam'
      responses:
        '204':
          description: 投稿の削除に成功
        '404':
          $ref: '#/components/responses/NotFound'
  /posts/{postId}/comments:
    get:
      description: 投稿に付いたコメントをすべて取得する
      operationId: getComments
      parameters:
        - $ref: '#/components/parameters/postIdParam'
      responses:
        '200':
          $ref: '#/components/responses/Comments'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      description: 投稿にコメントを付ける
      operationId: createComment
      parameters:
        - $ref: '#/components/parameters/postIdParam'
      requestBody:
        $ref: '#/components/requestBodies/Comment'
      responses:
        '201':
          $ref: '#/components/responses/Comment'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /posts/{postId}/comments/{commentId}:
    delete:
      description: 投稿に付いたコメントを削除する
      operationId: deleteComment
      parameters:
        - $ref: '#/components/parameters/postIdParam'
        - $ref: '#/components/parameters/commentIdParam'
      responses:
        '204':
          description: コメントの削除に成功
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Post:
      type: object
      properties:
        post:
          $ref: '#/components/schemas/PostProperties'
      required:
        - post
    PostRequest:
      type: object
      properties:
        post:
          $ref: '#/components/schemas/PostParameters'
      required:
        - post
    Posts:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/PostProperties'
      required:
        - posts
    PostProperties:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: こんにちは
        content:
          type: string
          example: 良い天気ですね
        posted_at:
          type: string
          format: date-time
          example: '2018-12-01T00:00:00Z'
      required:
        - id
        - title
        - content
        - posted_at
    PostParameters:
      type: object
      properties:
        title:
          type: string
          example: こんにちは
        content:
          type: string
          example: 良い天気ですね
      required:
        - title
        - content
    Comment:
      type: object
      properties:
        comment:
          $ref: '#/components/schemas/CommentProperties'
      required:
        - comment
    CommentRequest:
      type: object
      properties:
        comment:
          $ref: '#/components/schemas/CommentParameters'
      required:
        - comment
    Comments:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentProperties'
      required:
        - comments
    CommentProperties:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: そうですね
        post_id:
          type: integer
          example: 1
        commented_at:
          type: string
          format: date-time
          example: '2018-12-01T00:00:00Z'
      required:
        - id
        - content
        - post_id
        - commented_at
    CommentParameters:
      type: object
      properties:
        content:
          type: string
          example: そうですね
      required:
        - content
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorProperties'
      required:
        - errors
    ErrorProperties:
      type: object
      properties:
        title:
          type: string
          example: Something went wrong
        detail:
          type: string
          example: Something went wrong. Please try again later.
      required:
        - title
        - detail
  parameters:
    postIdParam:
      name: postId
      in: path
      description: 投稿のID
      required: true
      schema:
        type: integer
    commentIdParam:
      name: commentId
      in: path
      description: コメントのID
      required: true
      schema:
        type: integer
  requestBodies:
    Comment:
      description: 投稿に付けるコメント
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommentRequest'
    Post:
      description: 作成する投稿
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostRequest'
  responses:
    Comment:
      description: コメント
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comment'
    Comments:
      description: コメントの配列
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comments'
    Post:
      description: 投稿
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Post'
    Posts:
      description: 投稿の配列
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Posts'
    NotFound:
      description: リソースが見つからない
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnprocessableEntity:
      description: 無効なパラメータ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
