version: '3'

services:
  try-logrus-stackdriver:
    build: ./
    ports:
      - "8080:8080"
    restart: always
    environment:
      EXECUTION_ENVIRONMENT: gce
      GCP_PROJECT_ID: prism-test-216713
    logging:
      driver: gcplogs